version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 15
    reviewers:
      - fxhxyz4
    commit-message:
      prefix: fix
